config/routes.rb
Rails.application.routes.draw do
  resources :orders
  resources :line_items
  resources :carts
  root "products#index"

  resources :products do
    resources :reviews
    member do
      delete :delete_image_attachment
    end
  end
  namespace :products do
    post 'csv_upload'
  end

  resources :categories
  resources :sessions, only: [:create]
  
  resources :orders
  get '/orders/new_order', to: 'orders#new', as: 'orders_new'

  get 'signup', to: 'users#new', as: 'signup'
  get 'login', to: 'sessions#new', as: 'login'
  get 'logout', to: 'sessions#destroy', as: 'logout'

  get "myproducts", to: "products#myindex"
  get "myaccount", to: "users#myindex"

  scope "/admins" do
    resources :users
  end
  get "admins/users", to: "users#index"
  get "admins/allproducts", to: "products#allproducts"

end

app/views/admin/products.html.erb
<h1>Admin : All Shops</h1>

<h3>All shops have <%= @products.public_count %> products</h3>

<p id="notice"><%= notice %></p>

<table class="table">
    <tr>
        <th>Products</th>

        <th>Image</th>

        <th>Categories</th>

        <th>Price</th>

        <th>Stock</th>
    </tr>
  <% @products.each do |product| %>
    <tr>
        <% unless product.archived? %>
        <th>
            <%= link_to product.name, product %>
        </th>

        <th>
            <% if product.image.attached? %>
            <div style="width:100px; height:auto">
                <%= link_to image_tag(product.image, style:"width:100%") , product%>
            </div>
            <% end %>
        </th>

        <th> <%= product.categories.map(&:name).join(',') %></th>

        <th>
            <%= product.price %>
        </th>

        <th>
            <%= product.stock %>
        </th>
        <% end %>
    
        <th><%= link_to "Edit", edit_product_path(product) %></th>

        <th><%= link_to "Delete", product_path(product),
                  method: :delete,
                  data: { confirm: "Delete product '#{product.name}' ?" } %></th>
    </tr>
  <% end %>
</table>

<h3><%= link_to "New Product", new_product_path %></h3>
<h5> Or </h5>
<h3>Add products via CSV file</h3>

<%= form_tag products_csv_upload_path , multipart: true  do  %>
  <%= file_field_tag :csv_file  %>
  <%= submit_tag :submit  %>
<% end %>

app/views/admin/users.html.erb
<p id="notice"><%= notice %></p>

<h1>Users</h1>

<table>
  <thead>
    <tr>
      <th>Email</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.email %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Delete Account', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<hr>
<%= link_to 'New User', new_user_path %>
<hr>
<%= link_to 'Edit All Product', "/admins/products" %>