config/routes.rb
Rails.application.routes.draw do
  resources :orders
  resources :line_items
  resources :carts
  root "products#index"

  resources :products do
    resources :reviews
    member do
      delete :delete_image_attachment
    end
  end
  namespace :products do
    post 'csv_upload'
  end

  resources :categories
  resources :sessions, only: [:create]
  
  resources :orders
  get '/orders/new_order', to: 'orders#new', as: 'orders_new'

  get 'signup', to: 'users#new', as: 'signup'
  get 'login', to: 'sessions#new', as: 'login'
  get 'logout', to: 'sessions#destroy', as: 'logout'

  get "myproducts", to: "products#myindex"
  get "myaccount", to: "users#myindex"

  scope "/admins" do
    resources :users
  end
  get "admins/users", to: "users#index"
  get "admins/allproducts", to: "products#allproducts"

end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password

  validates :email, presence: true, uniqueness: true
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: %i[ show edit update destroy ]
  before_action :checkadmin, only: [:index]

  def index
    @users = User.all
  end

  def myindex
    @users = User.all.where(email: current_user.email)
  end

  def show
  end

  def new
    @user = User.new
  end

  def edit
  end

  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to root_path, notice: "User was successfully created. Please Login" }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: "User was successfully updated." }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: "User was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    def set_user
      @user = User.find(params[:id])
    end

    def user_params
      params.require(:user).permit(:email, :password, :password_confirmation, :role)
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<%= form_with(model: user) do |form| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
        <% user.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :"Username" %>
    <%= form.text_field :email %>
  </div>

  <div class="field">
    <%= form.label :password %>
    <%= form.password_field :password %>
  </div>

  <div class="field">
    <%= form.label :password_confirmation %>
    <%= form.password_field :password_confirmation %>
  </div>

  <%if current_user %> 
    <% if current_user.role == "admin" %>
      <div class="field">
        <%= form.label :role %>
        <%= form.select :role, ['admin', 'user'], selected: 'user' %>
      </div>
    <% end %>
  <% else %>
    <div>
      <%= form.hidden_field :role, :value => "user" %><br>
    </div>
  <% end %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form', user: @user %>

</br>

<% if current_user.role == "admin" %>
    <%= link_to 'Back', users_path %>
<% end %>

app/views/users/index.html.erb
<h1>Admin Page</h1>
<p> manage users and see all products including hiddens </p>

<h2>Users</h2>

<table>
  <thead>
    <tr>
      <th>Username</th>
      <th>Role</th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.email %></td>
        <td><%= user.role %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Delete Account', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

</br>
<%= link_to 'New User', new_user_path %>
<hr>
<h2><%= link_to 'Click to see All Products From All Users', "/admins/allproducts" %></h2>
<hr>
<h2><%= link_to 'Click to see All Orders From All Users', orders_path %></h2>

app/views/users/myindex.html.erb
<p id="notice"><%= notice %></p>

<h1>User</h1>

<table class="table">
    <% @users.each do |user| %>
      <tr>
        <td><h5><%= user.email %></h5></td>
        <td><h5><%= link_to 'Edit', edit_user_path(user) %><h5></td>
        <td><h5><%= link_to 'Delete Account', user, method: :delete, data: { confirm: 'Are you sure?' } %><h5></td>
      </tr>
    <% end %>
</table>

<br>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Email:</strong>
  <%= @user.email %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>