config/routes.rb
Rails.application.routes.draw do
  resources :orders
  resources :line_items
  resources :carts
  root "products#index"

  resources :products do
    resources :reviews
    member do
      delete :delete_image_attachment
    end
  end
  namespace :products do
    post 'csv_upload'
  end

  resources :categories
  resources :sessions, only: [:create]
  
  resources :orders
  get '/orders/new_order', to: 'orders#new', as: 'orders_new'

  get 'signup', to: 'users#new', as: 'signup'
  get 'login', to: 'sessions#new', as: 'login'
  get 'logout', to: 'sessions#destroy', as: 'logout'

  get "myproducts", to: "products#myindex"
  get "myaccount", to: "users#myindex"

  scope "/admins" do
    resources :users
  end
  get "admins/users", to: "users#index"
  get "admins/allproducts", to: "products#allproducts"

end

app/models/product.rb
class Product < ApplicationRecord
    include Visible
    before_destroy :not_referenced_by_any_line_item
    has_many :line_items

    has_many :reviews, dependent: :destroy

    has_many :categories_products
    has_many :categories, through: :categories_products

    has_one_attached :image
    has_many_attached :support_image

    validates :name, presence: true
    validates :description, presence: true, length: { minimum: 15 }
    validates :price, presence: true, numericality: {message: "Price must be possitive value!" ,in: 1..9999}
    validates :stock, presence: true, numericality: { only_integer: true ,message: "Stock must be possitive integer!" , in: 1..9999}


    private

    def not_refereced_by_any_line_item
        unless line_items.empty?
            errors.add(:base, "Line items present")
            throw :abort
        end
    end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :authorized, except: [:index, :show]
  before_action :checkadmin, only: [:allproducts]

  def index
    @products = Product.all.where(status: "public")

    respond_to do |format|
      format.html
      format.csv {send_data generate_csv(Product.all), file_name: 'products.csv'}
    end
  end

  def show
    @product = Product.find(params[:id])
  end

  def myindex
    @products = Product.all.where(owner: current_user.email)
  end

  def allproducts
    @products = Product.all

    respond_to do |format|
      format.html
      format.csv {send_data generate_csv(Product.all), file_name: 'products.csv'}
    end
  end

  def new
    @product = Product.new
  end

  def create
    @product = Product.new(product_params)
    if @product.save
      redirect_to @product
    else
      render :new
    end
  end

  def edit
    @product = Product.all.where(owner: current_user.email).find(params[:id])
  end

  def update
    @product = Product.all.where(owner: current_user.email).find(params[:id])
    if @product.update(product_params)
      redirect_to @product
    else
      render :edit
    end
  end

  def destroy
    @product = Product.find(params[:id])
    @product.destroy
    redirect_to root_path, notice: "A product deleted"
  end

  def csv_upload
    data = params[:csv_file].read.split("\n")
    data.each do |line|
      attr = line.split(",").map(&:strip)
      Product.create name: attr[0], description: attr[1], price: attr[2], stock: attr[3], status: "public", owner: current_user.email
    end
    redirect_to root_path 
  end

  def generate_csv(products)
    products.map do |product|
      [product.name, product.description,product.price, product.stock, product.status].join(',')
    end.join("\n")
  end

  def delete_image_attachment
    @space_image = ActiveStorage::Attachment.find(params[:id])
    @space_image.purge
    redirect_back(fallback_location: request.referer)
  end

  private
    def product_params
      params.require(:product).permit(:name, :description, :price, :stock, :owner, :status, :image, :category_ids=>[], :support_image=>[])
    end
end

app/views/products/_form.html.erb
<%= form_with model: product do |form| %>
  <div>
    <%= form.label :name%>
    <%= form.text_field :name %>
    <% product.errors.full_messages_for(:name).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>

  <% if product.image.attached? %>
  <div style="width:300px; height:auto">
      <%= link_to image_tag(product.image, style:"width:100%") , product%>
  </div>
  <%= link_to 'Remove', delete_image_attachment_product_url(product.image.id),
                  method: :delete,
                  data: { confirm: 'Are you sure?' } %>
  <% end %>

  <div>
    <%= form.label :description %><br>
    <%= form.text_area :description %><br>
    <% product.errors.full_messages_for(:description).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>

  <div>
    <%= form.label :categories %>
    <%= form.collection_select :category_ids, Category.order(:name), :id, :name, {}, class:"form-control", multiple: true    %>
  </div>

  <div>
    <%= form.label :price%><br>
    <%= form.number_field :price %><br>
    <% product.errors.full_messages_for(:price).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>

  <div>
    <%= form.label :stock %><br>
    <%= form.number_field :stock %><br>
    <% product.errors.full_messages_for(:stock).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>

  <div>
    <%= form.hidden_field :owner, :value => current_user.email %><br>
  </div>

  <div>
    <%= form.label :status %>
    <%= form.select :status, ['public', 'private', 'archived'], selected: 'public' %>
  </div>

  <hr>

  <% if product.image.attached? %>
    <h5>Change Main Image</h5>
    <%= form.label :image %>
    <%= form.file_field :image %>
  <% else %>
    <h5>Add Main Image</h5>
    <%= form.label :image %>
    <%= form.file_field :image %>
  <% end %>

  <hr>

  <% if product.support_image.attached? %>
    <h5> Support Images </h5>
    <% @product.support_image.each do |support_image| %>
        <div style="width:100px; height:auto">
            <%= image_tag(support_image, style:"width:100%") %>
        </div>
        <%= link_to 'Remove', delete_image_attachment_product_url(support_image.id),
                  method: :delete,
                  data: { confirm: 'Are you sure?' } %>
    <% end %>

    <h5>Change Support Images</h5>
    <%= form.label :support_image %>
    <%= form.file_field :support_image ,multiple: true%>
  <% else %>
    <h5>Add Support Images</h5>
    <%= form.label :support_image %>
    <%= form.file_field :support_image ,multiple: true%>
  <% end %>

  <hr>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/products/admins.html.erb
<h1>All Shops</h1>

<h3>All shops have <%= @products.public_count %> products</h3>

<p id="notice"><%= notice %></p>

<table class="table">
    <tr>
        <th>Products</th>

        <th>Image</th>

        <th>Categories</th>

        <th>Price</th>

        <th>Stock</th>
    </tr>
  <% @products.each do |product| %>
    <tr>
        <% unless product.archived? %>
        <th>
            <%= link_to product.name, product %>
        </th>

        <th>
            <% if product.image.attached? %>
            <div style="width:100px; height:auto">
                <%= link_to image_tag(product.image, style:"width:100%") , product%>
            </div>
            <% end %>
        </th>

        <th> <%= product.categories.map(&:name).join(',') %></th>

        <th>
            <%= product.price %>
        </th>

        <th>
            <%= product.stock %>
        </th>
        <% end %>
    
        <th><%= link_to "Edit", edit_product_path(product) %></th>

        <th><%= link_to "Delete", product_path(product),
                  method: :delete,
                  data: { confirm: "Delete product '#{product.name}' ?" } %></th>
    </tr>
  <% end %>
</table>

<h3><%= link_to "New Product", new_product_path %></h3>
<h5> Or </h5>
<h3>Add products via CSV file</h3>

<%= form_tag products_csv_upload_path , multipart: true  do  %>
  <%= file_field_tag :csv_file  %>
  <%= submit_tag :submit  %>
<% end %>

app/views/products/allproducts.html.erb
<h1>All Shops</h1>
<h3>All shops have <%= @products.public_count %> products</h3>

<p id="notice"><%= notice %></p>

<table class="table">
    <tr>
        <th>Products</th>

        <th>Image</th>

        <th>Categories</th>

        <th>Price</th>

        <th>Stock</th>
    </tr>
  <% @products.each do |product| %>
    <tr>
        <% unless product.archived? %>
        <th>
            <%= link_to product.name, product %>
        </th>

        <th>
            <% if product.image.attached? %>
            <div style="width:100px; height:auto">
                <%= link_to image_tag(product.image, style:"width:100%") , product%>
            </div>
            <% end %>
        </th>

        <th> <%= product.categories.map(&:name).join(',') %></th>

        <th>
            <%= product.price %>
        </th>

        <th>
            <%= product.stock %>
        </th>
        <% end %>

        <th><%= link_to "Delete", product_path(product),
                  method: :delete,
                  data: { confirm: "Delete product '#{product.name}' ?" } %></th>
    </tr>
  <% end %>
</table>

<h3><%= link_to "New Product", new_product_path %></h3>
<h5> Or </h5>
<h3>Add products via CSV file</h3>

<%= form_tag products_csv_upload_path , multipart: true  do  %>
  <%= file_field_tag :csv_file  %>
  <%= submit_tag :submit  %>
<% end %>

app/views/products/edit.html.erb
<h1>Edit Product Details</h1>

<%= render "form", product: @product %>

app/views/products/index.html.erb
<h1>Welcome to Urn Shopping!</h1>

<h3>Our shops have <%= Product.public_count %> products for sale! </h3>

<p id="notice"><%= notice %></p>

<div class="flex-container">
  <% @products.each do |product| %>
    <div class="card" style="width: 300px; margin:10px; display:inline-block;">
        <div class="card-body">
            <h4 class="card-title"><%= link_to product.name, product %></h4>
            <div style="height:200px">
            <% if product.image.attached? %>
                <%= link_to image_tag(product.image, style:"width:200px; height:200px") , product%>
            <% end %>
            </div>
            <p>Categories : <%= product.categories.map(&:name).join(',') %></p>
            <div class="row">
                <div class="col-md">
                    <p>Price : <%=product.price%></p>
                </div>
                <div class="col-md">
                    <p>Stock : <%=product.stock%></p>
                </div>
            </div>
            <div class="row">
                <div class="col-md">
                    <div><%= link_to 'Buy Now', new_order_path(product_id: product), class: 'btn btn-warning' %></div>
                </div>
                <div class="col-md">
                    <div><%= link_to "More Detail", product ,class:"btn btn-info" %></div>
                </div>
            </div>
        </div>
    </div>
  <% end %>
</div>

<div>
    <%= link_to 'Download CSV File ', products_path(format: :csv), class: "btn btn-outline-info"%>
</div>
</br>
<p> Go to 'My Products' to add your new product </p>
<p> For TA : For managing users login with ID:admin Pass:88998899</p>
<p> Managing orders can be found in 'Admin' page </p>
<p> Ordering with items in cart, TBA </p>

app/views/products/myindex.html.erb
<h1>My Shop</h1>

<h3>My shop has <%= @products.public_count %> products</h3>

<p id="notice"><%= notice %></p>

<table class="table">
    <tr>
        <th>Products</th>

        <th>Image</th>

        <th>Categories</th>

        <th>Price</th>

        <th>Stock</th>
    </tr>
  <% @products.each do |product| %>
    <tr>
        <% unless product.archived? %>
        <th>
            <%= link_to product.name, product %>
        </th>

        <th>
            <% if product.image.attached? %>
            <div style="width:100px; height:auto">
                <%= link_to image_tag(product.image, style:"width:100%") , product%>
            </div>
            <% end %>
        </th>

        <th> <%= product.categories.map(&:name).join(',') %></th>

        <th>
            <%= product.price %>
        </th>

        <th>
            <%= product.stock %>
        </th>
        <% end %>
    
        <th><%= link_to "Edit", edit_product_path(product) %></th>

        <th><%= link_to "Delete", product_path(product),
                  method: :delete,
                  data: { confirm: "Delete product '#{product.name}' ?" } %></th>
    </tr>
  <% end %>
</table>

<h3><%= link_to "New Product", new_product_path %></h3>
<h5> Or </h5>
<h3>Add products via CSV file</h3>

<%= form_tag products_csv_upload_path , multipart: true  do  %>
  <%= file_field_tag :csv_file  %>
  <%= submit_tag :submit  %>
<% end %>

app/views/products/new.html.erb
<h1>New Product</h1>

<%= render "form", product: @product %>

app/views/products/show.html.erb
<div class="container bg-light" style="margin:20px;">
    <div class="row" style="height:100px;">
        <div style="padding:20px;"><h1><%= @product.name %></h1></div>
    </div>
    <div class="row" style="height:340px">
        <div class="col" style="height:300px ">
            <div class="container">
            <% if @product.image.attached? %>
                <div style="height:300px; object-fit:contain;">
                    <%=image_tag(@product.image)%>
                </div>
            <% end %>
            </div>
        </div>
        <div class="col">
            <div class="row" style="padding:20px;"><h4>sold : <%= @product.sold %></h4></div>
            <div class="row" style="padding:20px; color:orange"><h1>price : <b><%= @product.price %></b><h1></div>
            <div class="row" style="padding:20px;">left : <%= @product.stock %></div>
            <div class="row" style="padding:20px;"> <%= button_to 'Add to Cart', line_items_path(product_id: @product), class: 'btn btn-success' %>
                                                    <%= link_to 'Buy Now', new_order_path(product_id: @product), class: 'btn btn-warning' %></div>
        </div>
    </div>
</div>

<div class="container bg-warning" style="height:80px; margin:20px;">
    <div style="padding:25px "><h4>Seller : <%= @product.owner %></h4></div>
</div>

<div class="container bg-light" style="margin:20px;">
    <div style="padding:30px "> Categories : <%= @product.categories.map(&:name).join(',') %></div>
    <div style="padding:30px "> Description : <%= @product.description %></div>
    <div style="padding:30px "> More Images :
        <% if @product.support_image.attached? %>
            <% @product.support_image.each do |support_image| %>
                <div style="width:100px; height:100px; object-fit: contain;">
                    <%= image_tag(support_image, style:"width:100%") %>
                </div>
            <% end %>
        <% end %>
    </div>
</div>

<div class="container bg-light" style="margin:20px; padding:20px">
    <h2>Reviews</h2>
        <%= render @product.reviews %>

    <h5>Add a review:</h5>
        <%= render 'reviews/form' %>
</div>

<div class="container" style="margin:20px;">
<%= link_to "Back to Products", '/products', class:"btn btn-outline-info"%>
</div>